# -*- coding: utf-8 -*-
"""stockPricePredictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13BD8gALpdPH2owf1CudF-QvEdrvXeOQW
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt

# Data
stock_data = pd.read_csv('stock_prices.csv')

# Preprocessing

features = ['Open', 'Close', 'Volume']
target = 'Adj Close'
X = stock_data[features]
y = stock_data[target]

# Spliting the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Training the Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

# Evaluate the Model
mse_train = mean_squared_error(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)

print(y_pred_test)
print(y_pred_train)
print(mse_test)
print(mse_train)